### PR TITLE
2.8.1-1

### PR DESCRIPTION
**Pull request by chrschroeder**
Several upstream imports. Since the build system was changed to maven I installed the precompiled jar files from the tar.gz release instead of rebuilding it from scratch.

### CODE REVIEW

**Comment by mdavidsaver** [comment]
Did you encounter some problem with building from source with maven?

https://wiki.debian.org/Java/Packaging#Maven

https://wiki.debian.org/Java/MavenRepoHelper

**Comment by chrschroeder** [comment]
It's a while ago, but I tried to convert the project with the helper scripts indeed. The build failed at some point, unfortunately I don't remember where. I decided, that rebuilding the jar is not really necessary and that this attempt would be much simpler. Does this conflict with the debian policy?

**Comment by chrschroeder** [comment]
Update: I had a look at MavenRepoHelper again and created a version working for Debian 9 (see: https://github.com/chrschroeder/visualdct-test.git).

For Debian 10 the dependency libmysql-java is missing. In place of this package there is a libmariadb-java. Simply patching the dependency in the control file doesn't work, since the references still point to mysql.

**Comment by mark0n** [comment]
You can say `libmysql-java | libmariadb-java` in the `control` file. I'm not a Java/Maven guy but maybe there is a way to specify which one to use (e.g. a command-line argument or an environment variable)? Maybe some magic in the `rules` file could detect which one is installed and populate the environment variable accordingly?

**Comment by mdavidsaver** [comment]
Moving past the question of wtf is visualdct connecting to mysql...  The following is enough for my to build and run locally on Debian 10.  I'm not planning to test that the rdb plugin works.

```sh
mvn compile -o -Dmaven.repo.local=/usr/share/maven-repo
java -jar target/VisualDCT-2.8.2-SNAPSHOT.jar
```

After installing a pile of maven plugins.  Some of these may not be necessary.

```sh
apt-get install libmaven-compiler-plugin-java libmariadb-java \
  libmaven-javadoc-plugin-java libmaven-jar-plugin-java \
  libmaven-source-plugin-java libmaven-assembly-plugin-java \
  libmaven-site-plugin-java libmaven-resources-plugin-java \
  libmaven-install-plugin-java
```



```diff
diff --git a/pom.xml b/pom.xml
index f00ca62..be3ca3a 100644
--- a/pom.xml
+++ b/pom.xml
@@ -55,9 +55,9 @@
 
     <dependencies>
         <dependency>
-            <groupId>mysql</groupId>
-            <artifactId>mysql-connector-java</artifactId>
-            <version>5.1.46</version>
+            <groupId>org.mariadb.jdbc</groupId>
+            <artifactId>mariadb-java-client</artifactId>
+            <version>debian</version>
         </dependency>
     </dependencies>
 
@@ -66,7 +66,7 @@
 
             <plugin>
                 <artifactId>maven-jar-plugin</artifactId>
-                <version>3.1.0</version>
+                <version>3.1.1</version>
                 <configuration>
                     <archive>
                         <manifest>
diff --git a/src/main/java/com/cosylab/vdct/rdb/RdbConnection.java b/src/main/java/com/cosylab/vdct/rdb/RdbConnection.java
index 9da08bc..c672fda 100644
--- a/src/main/java/com/cosylab/vdct/rdb/RdbConnection.java
+++ b/src/main/java/com/cosylab/vdct/rdb/RdbConnection.java
@@ -56,7 +56,7 @@ public class RdbConnection {
      * @throws Exception foo
      */
     public RdbConnection() throws Exception {
-               Class.forName("com.mysql.jdbc.Driver").newInstance();
+               Class.forName("org.mariadb.jdbc.Driver").newInstance();
        }
        
     /**
@@ -96,7 +96,7 @@ public class RdbConnection {
      */
     public Connection createConnection() throws SQLException {
                connection = null;
-               String connectionString = "jdbc:mysql://" + host + "/" + database
+               String connectionString = "jdbc:mariadb://" + host + "/" + database
                + "?user=" + user + "&password=" + password;
 
                connection = DriverManager.getConnection(connectionString);
```

@ralphlange fyi

**Comment by mdavidsaver** [comment]
As a note for anyone trying to troubleshoot those irritatingly incomplete `Could not resolve dependencies for` messages.  I resorted to strace to see what file maven was trying to open.

eg. Simply running "mvn compile -o" fails with

```
[ERROR] Plugin org.apache.maven.plugins:maven-source-plugin:3.0.1 or one of its dependencies could not be resolved: Cannot access central (https://repo.maven.apache.org/maven2) in offline mode and the artifact org.apache.maven.plugins:maven-source-plugin:jar:3.0.1 has not been downloaded from it before. -> [Help 1]
```

Running:

```sh
strace -e trace=%file -f mvn compile -o
```

```
[pid 24045] stat("/home/mdavidsaver/.m2/repository/org/apache/maven/plugins/maven-source-plugin/3.0.1/maven-source-plugin-3.0.1
```

Shows that it is looking under `$HOME` because I omitted `-Dmaven.repo.local=/usr/share/maven-repo`.

**Comment by chrschroeder** [comment]
Well mh_make suggested to put the maven-source-plugin on the ignore list because "This plugin is not useful for the build or its use is against Debian policies."

I updated the test repository https://github.com/chrschroeder/visualdct-test with Michaels changes. Unfortunately the patch will make it incompatible with stretch, because there is no mariadb. 

Does anyone know, if it is possible to make specific patches optional in the quilt 3.0 format of debian packages? Otherwise one would have to remove the patch from the series file before building for stretch. Not much work, but I would like to have a solution which works automatically.

**Pull request closed without merging**
